version: "3.8"

services: 

  # ros1-build:
  #   build: .
  #   image: demo
  #   command: -c "cd ~/workspace1 && make build"
  #   volumes:
  #     - ~/Desktop/tirocinio/shelfino/projects:/home/ros2/workspace1

  # shelfino:
  #   build: .
  #   image: demo
  #   restart: unless-stopped
  #   network_mode: host
  #   command: -c "cd ~/workspace1 && make run"
  #   depends_on:
  #     - ros1-build
  #   volumes:
  #     - ~/Desktop/tirocinio/shelfino/projects:/home/ros2/workspace1

  # bridge:
  #   build: .
  #   image: demo
  #   restart: unless-stopped
  #   network_mode: host
  #   command: -c "cd ~/workspace2 && make bridge"
  #   depends_on:
  #     - shelfino
  #   volumes:
  #     - ~/Desktop/tirocinio/shelfino/ground-robots:/home/ros2/workspace2


  ros2-build-workspace2:
    build: .
    image: demo
    command: -c "cd ~/workspace2 && make build"
    volumes:
      - ~/Desktop/tirocinio/shelfino/ground-robots:/home/ros2/workspace2

  navigation:
    build: .
    image: demo
    restart: unless-stopped
    network_mode: host
    command: -c "cd ~/workspace2 && make sim"
    depends_on: 
      ros2-build-workspace2:
        condition: service_completed_successfully
    environment:
      - DISPLAY=:0
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros2/fastrtps-profile.xml
    volumes:
      - ~/Desktop/tirocinio/shelfino/ground-robots:/home/ros2/workspace2
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/dri/card0:/dev/dri/card0

  planning-bridge:
    image: demo
    restart: unless-stopped
    network_mode: host
    command: -c "cd ~/workspace2 && sleep 10 && make planning"
    depends_on:
      ros2-build-workspace2:
        condition: service_completed_successfully
      navigation:
        condition: service_started
      planning:
        condition: service_started
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros2/fastrtps-profile.xml
    volumes:
      - ~/Desktop/tirocinio/shelfino/ground-robots:/home/ros2/workspace2


  ros2-build-planning:
    build: .
    image: demo
    command: -c "cd ~/planning && make build"
    volumes:
      - ~/Desktop/tirocinio/shelfino/planning:/home/ros2/planning

  planning:
    build: .
    image: demo
    restart: unless-stopped
    network_mode: host
    command: -c "cd ~/planning && make run"
    depends_on:
      ros2-build-planning:
        condition: service_completed_successfully
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros2/fastrtps-profile.xml
    volumes:
      - ~/Desktop/tirocinio/shelfino/planning:/home/ros2/planning

  webserver:
    build: .
    image: demo
    restart: unless-stopped
    network_mode: host
    command: -c "cd ~/planning && make webserver"
    volumes:
      - ~/Desktop/tirocinio/shelfino/planning:/home/ros2/planning
